// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionsTech.Data.Context;

#nullable disable

namespace SolutionsTech.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionsTech.Business.Entity.Brand", b =>
                {
                    b.Property<long>("IdBrand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdBrand"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDesativation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBrand");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("SolutionsTech.Business.Entity.FormPayment", b =>
                {
                    b.Property<long>("IdFormPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFormPayment"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDesativation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFormPayment");

                    b.ToTable("FormPayment");
                });

            modelBuilder.Entity("SolutionsTech.Business.Entity.Product", b =>
                {
                    b.Property<long>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdProduct"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDesativation")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdBrand")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduct");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SolutionsTech.Business.Entity.Scheduling", b =>
                {
                    b.Property<long>("IdScheduling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdScheduling"));

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDesativation")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdFormPayment")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdScheduling");

                    b.ToTable("Scheduling");
                });

            modelBuilder.Entity("SolutionsTech.Business.Entity.SchedulingProcedure", b =>
                {
                    b.Property<long>("IdSchedulingProcedure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSchedulingProcedure"));

                    b.Property<long>("IdScheduling")
                        .HasColumnType("bigint");

                    b.Property<long>("IdTypeProcedure")
                        .HasColumnType("bigint");

                    b.HasKey("IdSchedulingProcedure");

                    b.ToTable("SchedulingProcedure");
                });

            modelBuilder.Entity("SolutionsTech.Business.Entity.SchedulingProduct", b =>
                {
                    b.Property<long>("IdSchedulingProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSchedulingProduct"));

                    b.Property<long>("IdProduct")
                        .HasColumnType("bigint");

                    b.Property<long>("IdScheduling")
                        .HasColumnType("bigint");

                    b.HasKey("IdSchedulingProduct");

                    b.ToTable("SchedulingProduct");
                });

            modelBuilder.Entity("SolutionsTech.Business.Entity.TypeProcedure", b =>
                {
                    b.Property<long>("IdTypeProcedure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdTypeProcedure"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTypeProcedure");

                    b.ToTable("TypeProcedure");
                });

            modelBuilder.Entity("SolutionsTech.Business.Entity.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUser"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtBorn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtCreate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtDeactivation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdUserType")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SolutionsTech.Business.Entity.UserType", b =>
                {
                    b.Property<long>("IdUserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUserType"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUserType");

                    b.ToTable("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
